import { MODEL_GROUPS, THINKING_CHOICES, OUTPUT_ENERGY_WH_PER_TOKEN, REFERENCES } from './parameters.js';
import { estimateConversation } from './core.js';
import { parseFile, parsePasted } from './importer.js';
import { downloadText,jsonText,csvText,htmlText } from './report.js';

const $=s=>document.querySelector(s);
let conversations=[], currentEstimate=null, droppedFile=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function fmt(n,d=2){return Number.isFinite(n)?n.toFixed(d):'—';}
function initModels(){const select=$('#model');for(const [group,models] of MODEL_GROUPS){const optg=document.createElement('optgroup');optg.label=group;for(const [name] of models){const o=document.createElement('option');o.value=o.textContent=name;if(name==='GPT-5.6 Sol')o.selected=true;optg.appendChild(o);}select.appendChild(optg);}const wrap=$('#thinking');for(const name of THINKING_CHOICES){const label=document.createElement('label');label.className='seg';const input=document.createElement('input');input.type='radio';input.name='thinking';input.value=name;if(name==='Standard / none')input.checked=true;const span=document.createElement('span');span.textContent=name.replace('Standard / none','Standard');label.append(input,span);wrap.appendChild(label);}}
function thinking(){return $('input[name="thinking"]:checked')?.value||'Standard / none';}
function status(html,type='info'){$('#import-status').innerHTML=`<div class="notice ${type}">${html}</div>`;}
function clearResult(){$('#results').hidden=true;currentEstimate=null;}
async function inspect(){clearResult();const file=droppedFile||$('#file').files[0],pasted=$('#paste').value.trim();if(!file&&!pasted){status('Choose an export file or paste a transcript first.','warn');return;}const btn=$('#inspect');btn.disabled=true;btn.textContent='Inspecting locally…';try{conversations=file?await parseFile(file):[];if(!conversations.length&&pasted)conversations=parsePasted(pasted);if(!conversations.length){status('No conversation was recognized. For pasted text, use labels such as <b>User:</b> and <b>Assistant:</b>.','warn');return;}const sel=$('#conversation');sel.innerHTML='';conversations.forEach((c,i)=>{const n=c.messages.filter(m=>m.role==='assistant').length;const o=document.createElement('option');o.value=i;o.textContent=`${c.title} · ${c.provider} · ${n} responses`;sel.appendChild(o);});sel.disabled=false;$('#analyze').disabled=false;const c=conversations[0];status(`<b>${esc(c.provider)}</b> detected · ${esc(c.source_format)} · ${c.messages.length} visible messages. <span class="muted">Processing stays inside this browser.</span>`,'ok');}catch(e){console.error(e);status(`<b>Import error:</b> ${esc(e.message||e)}`,'warn');}finally{btn.disabled=false;btn.textContent='Inspect conversation';}}
function analyze(){if(!conversations.length)return;const c=conversations[Number($('#conversation').value)||0];currentEstimate=estimateConversation(c,$('#model').value,thinking());render(currentEstimate);}
function render(est){$('#results').hidden=false;$('#water').textContent=`${fmt(est.total_water_ml)} mL`;$('#range').textContent=`${fmt(est.scenario_low_ml)}–${fmt(est.scenario_high_ml)} mL`;$('#energy').textContent=`${fmt(est.total_energy_wh,3)} Wh`;$('#turn-count').textContent=est.turns.length;$('#direct').textContent=`${fmt(est.direct_water_ml)} mL`;$('#indirect').textContent=`${fmt(est.electricity_water_ml)} mL`;$('#model-class').textContent=`${est.model_class} · ${(OUTPUT_ENERGY_WH_PER_TOKEN[est.model_class]*1000).toFixed(2)} Wh / 1000 output tokens`;const share=est.total_water_ml?100*est.direct_water_ml/est.total_water_ml:0;$('#split-direct').style.width=`${share}%`;$('#split-indirect').style.width=`${100-share}%`;const t=est.tools;$('#tools').innerHTML=[['Web searches',t.web],['Code runs',t.code],['Input images',t.image_in],['Generated images',t.image_out],['Videos',t.video],['Documents',t.document]].map(([k,v])=>`<div class="tool-chip"><span>${esc(k)}</span><b>${v}</b></div>`).join('');$('#warnings').innerHTML=est.warnings.map(w=>`<div class="notice warn">${esc(w)}</div>`).join('');renderBars(est.turns);renderTable(est.turns);$('#results').scrollIntoView({behavior:'smooth',block:'start'});}
function renderBars(turns){const box=$('#bars');box.innerHTML='';const max=Math.max(0.001,...turns.map(t=>t.total_water_ml));for(const t of turns){const row=document.createElement('div');row.className='bar-row';row.innerHTML=`<div class="bar-label">${t.turn}</div><div class="bar-track"><div class="bar-fill"></div></div><div class="bar-value">${fmt(t.total_water_ml,2)} mL</div>`;row.querySelector('.bar-fill').style.width=`${Math.max(1,100*t.total_water_ml/max)}%`;box.appendChild(row);}}
function renderTable(turns){$('#turns-body').innerHTML=turns.map(t=>`<tr><td>${t.turn}</td><td>${t.input_tokens.toLocaleString()}</td><td>${t.output_tokens.toLocaleString()}</td><td>${fmt(t.text_energy_wh,4)}</td><td>${fmt(t.tool_energy_wh,4)}</td><td>${fmt(t.total_water_ml,3)}</td><td class="prompt-cell">${esc(t.user_excerpt)}</td></tr>`).join('');}
function setupDrop(){const dz=$('#dropzone'),input=$('#file');['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag');}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag');}));dz.addEventListener('drop',e=>{if(e.dataTransfer.files.length){droppedFile=e.dataTransfer.files[0];updateFile();}});dz.addEventListener('click',e=>{if(e.target!==input)input.click();});input.addEventListener('change',()=>{droppedFile=null;updateFile();});function updateFile(){const f=droppedFile||input.files[0];$('#file-name').textContent=f?`${f.name} · ${(f.size/1024).toFixed(0)} KB`:'Choose a file or drop it here';}}
function setupDownloads(){$('#download-json').onclick=()=>currentEstimate&&downloadText('prompt2water-estimate.json',jsonText(currentEstimate),'application/json');$('#download-csv').onclick=()=>currentEstimate&&downloadText('prompt2water-turns.csv',csvText(currentEstimate),'text/csv');$('#download-html').onclick=()=>currentEstimate&&downloadText('prompt2water-report.html',htmlText(currentEstimate),'text/html');$('#print').onclick=()=>window.print();}
function setupRefs(){$('#references').innerHTML=REFERENCES.map(([n,u])=>`<li><a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(n)}</a></li>`).join('');}
function sample(){const txt=`User: Explain in two paragraphs why data centres use water.\nAssistant: Data centres use water mainly for cooling and indirectly through electricity generation. Evaporative systems remove heat efficiently by transferring it to water, while power plants can also consume water when generating electricity.\nUser: Search the web and summarize one recent estimate.\nAssistant: I searched the web and found a recent production-scale estimate. The exact value depends strongly on model, infrastructure, and accounting boundaries.`;$('#paste').value=txt;$('#file').value='';droppedFile=null;$('#file-name').textContent='Choose a file or drop it here';inspect();}
initModels();setupDrop();setupDownloads();setupRefs();$('#inspect').onclick=inspect;$('#analyze').onclick=analyze;$('#sample').onclick=sample;
