const MAX_FILES=5000, MAX_UNCOMPRESSED=400*1024*1024;
function u16(v,o){return v.getUint16(o,true)} function u32(v,o){return v.getUint32(o,true)}
function safePath(name){name=name.replace(/\\/g,'/');if(name.startsWith('/')||name.split('/').includes('..'))return null;return name;}
async function inflateRaw(bytes){if(typeof DecompressionStream==='undefined')throw new Error('This browser does not support local ZIP decompression. Please use a modern browser.');const ds=new DecompressionStream('deflate-raw');return new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(ds)).arrayBuffer());}
async function gunzip(bytes){if(typeof DecompressionStream==='undefined')throw new Error('This browser does not support local GZIP decompression.');const ds=new DecompressionStream('gzip');return new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(ds)).arrayBuffer());}
export async function readZip(buffer){const b=new Uint8Array(buffer),v=new DataView(buffer);let eocd=-1;for(let i=b.length-22;i>=Math.max(0,b.length-22-65535);i--){if(u32(v,i)===0x06054b50){eocd=i;break;}}if(eocd<0)throw new Error('Invalid ZIP archive.');const n=u16(v,eocd+10),cd=u32(v,eocd+16);if(n>MAX_FILES)throw new Error('Archive contains too many files.');let p=cd,total=0;const out=[];const dec=new TextDecoder();for(let i=0;i<n;i++){if(u32(v,p)!==0x02014b50)throw new Error('Invalid ZIP central directory.');const flags=u16(v,p+8),method=u16(v,p+10),csize=u32(v,p+20),usize=u32(v,p+24),fnl=u16(v,p+28),exl=u16(v,p+30),col=u16(v,p+32),lho=u32(v,p+42);if(flags&1)throw new Error('Encrypted ZIP files are not supported.');const name=safePath(dec.decode(b.slice(p+46,p+46+fnl)));p+=46+fnl+exl+col;if(!name||name.endsWith('/'))continue;total+=usize;if(total>MAX_UNCOMPRESSED)throw new Error('Archive is too large after decompression.');if(u32(v,lho)!==0x04034b50)throw new Error('Invalid ZIP local header.');const lfn=u16(v,lho+26),lex=u16(v,lho+28),start=lho+30+lfn+lex,comp=b.slice(start,start+csize);let data;if(method===0)data=comp;else if(method===8)data=await inflateRaw(comp);else continue;out.push({name,data});}return out;}
function readAscii(bytes,start,len){return new TextDecoder().decode(bytes.slice(start,start+len)).replace(/\0.*$/s,'').trim();}
export function readTar(bytes){const out=[];let p=0,total=0;while(p+512<=bytes.length&&out.length<MAX_FILES){const block=bytes.slice(p,p+512);if(block.every(x=>x===0))break;const name0=readAscii(block,0,100),prefix=readAscii(block,345,155),name=safePath(prefix?prefix+'/'+name0:name0),size=parseInt(readAscii(block,124,12)||'0',8)||0,type=String.fromCharCode(block[156]||48);p+=512;if(name&&(type==='0'||type==='\0')&&size>=0){total+=size;if(total>MAX_UNCOMPRESSED)throw new Error('Archive is too large after decompression.');out.push({name,data:bytes.slice(p,p+size)});}p+=Math.ceil(size/512)*512;}return out;}
export async function readArchive(file){const buf=await file.arrayBuffer(),bytes=new Uint8Array(buf),name=file.name.toLowerCase();if(bytes[0]===0x50&&bytes[1]===0x4b)return readZip(buf);if(name.endsWith('.tgz')||name.endsWith('.tar.gz')||(bytes[0]===0x1f&&bytes[1]===0x8b))return readTar(await gunzip(bytes));if(name.endsWith('.tar'))return readTar(bytes);return null;}
