import { readArchive, readZip } from './archive.js';
import { parseChatGPT,parseClaude,parseGeminiJson,parseGenericJson,parseRoleText,parseHtmlConversation,providerHint } from './parsers.js';

const decoder=new TextDecoder('utf-8',{fatal:false});
const SUPPORTED=new Set(['.json','.jsonl','.html','.htm','.txt','.md','.log','.docx']);
function ext(name){const m=name.toLowerCase().match(/(\.tar\.gz|\.jsonl|\.docx|\.[^.]+)$/);return m?m[1]:'';}
function xmlText(xml){if(typeof DOMParser==='undefined')return [...String(xml).matchAll(/<w:t[^>]*>([\s\S]*?)<\/w:t>/g)].map(m=>m[1].replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>')).join(' ');const doc=new DOMParser().parseFromString(xml,'application/xml');return [...doc.getElementsByTagNameNS('*','t')].map(x=>x.textContent||'').join(' ');}
async function parseDocx(bytes,name){try{const entries=await readZip(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));const doc=entries.find(e=>e.name==='word/document.xml');if(!doc)return[];const text=xmlText(decoder.decode(doc.data));return parseRoleText(text,providerHint(name,text),'docx');}catch{return[];}}
function parseJson(name,text){let payload;try{if(name.toLowerCase().endsWith('.jsonl'))payload=text.split(/\r?\n/).filter(x=>x.trim()).map(x=>JSON.parse(x));else payload=JSON.parse(text);}catch{return[];}let c=parseChatGPT(payload);if(c.length)return c;c=parseClaude(payload);if(c.length)return c;c=parseGeminiJson(payload);if(c.length)return c;return parseGenericJson(payload,providerHint(name,text));}
export async function parseNamedBytes(name,bytes){const e=ext(name);if(!SUPPORTED.has(e))return[];if(e==='.docx')return parseDocx(bytes,name);const text=decoder.decode(bytes);if(e==='.json'||e==='.jsonl')return parseJson(name,text);if(e==='.html'||e==='.htm')return parseHtmlConversation(text,providerHint(name,text));return parseRoleText(text,providerHint(name,text),e.slice(1));}
export async function parseFile(file){const archive=await readArchive(file);if(archive){const prioritized=[...archive].sort((a,b)=>{const pa=/conversation|myactivity/i.test(a.name)?0:1,pb=/conversation|myactivity/i.test(b.name)?0:1;return pa-pb||a.name.localeCompare(b.name)});const out=[];for(const ent of prioritized){if(!SUPPORTED.has(ext(ent.name)))continue;const parsed=await parseNamedBytes(ent.name,ent.data);out.push(...parsed);if(parsed.some(c=>['chatgpt-export-json','claude-export-json'].includes(c.source_format)))break;}return dedupe(out);}const bytes=new Uint8Array(await file.arrayBuffer());return dedupe(await parseNamedBytes(file.name,bytes));}
export function parsePasted(text){return parseRoleText(text,'Unknown','pasted-text');}
function dedupe(convs){const seen=new Set(),out=[];for(const c of convs){const sig=[c.provider,c.title,c.messages.length,c.messages[0]?.text?.slice(0,100)].join('|');if(!seen.has(sig)){seen.add(sig);out.push(c);}}return out;}
