import { toolCounts, addTools } from './core.js';

const ROLE_RE=/^\s*(user|human|you|assistant|ai|claude|chatgpt|gemini|grok|deepseek)\s*:\s*/gim;
const P={web:[/searched the web/gi,/web search/gi,/search(?:ed|ing)? for\s+["']/gi,/browser\.search/gi,/search_query/gi],code:[/code interpreter/gi,/executed (?:the )?code/gi,/python execution/gi,/tool(?:_call)?[^\n]{0,30}python/gi],image_out:[/generated (?:an |the )?image/gi,/image generation/gi,/created (?:an |the )?image/gi],video:[/generated (?:a |the )?video/gi,/video generation/gi,/created (?:a |the )?video/gi],document:[/uploaded (?:a |the )?(?:pdf|document|file)/gi,/\.pdf\b/gi,/\.docx\b/gi],image_in:[/uploaded (?:an |the )?image/gi,/attached image/gi,/\[image\]/gi]};
function countPatterns(text,arr){let n=0;for(const r0 of arr){const r=new RegExp(r0.source,r0.flags);n += [...text.matchAll(r)].length;}return n;}
export function visibleToolsFromText(text=''){return toolCounts(Object.fromEntries(Object.entries(P).map(([k,v])=>[k,countPatterns(text,v)])));}
export function normalRole(role){if(role&&typeof role==='object')role=role.role||role.name||role.type;const r=String(role||'').toLowerCase();if(['user','human','you'].includes(r))return'user';if(['assistant','ai','bot','model','claude','chatgpt','gemini','grok','deepseek'].includes(r))return'assistant';return r;}
function flattenContent(value){let tools=toolCounts();if(value==null)return['',tools];if(typeof value==='string')return[value,visibleToolsFromText(value)];if(['number','boolean'].includes(typeof value))return[String(value),tools];if(Array.isArray(value)){const texts=[];for(const x of value){const[t,tc]=flattenContent(x);tools=addTools(tools,tc);if(t)texts.push(t);}return[texts.join('\n'),tools];}if(typeof value==='object'){const typ=String(value.type||value.content_type||'').toLowerCase();if(typ.includes('image'))return['[image]',tools];if(typ.includes('video'))return['[video]',tools];if(typ.includes('tool_use')||typ.includes('tool_call')){const name=String(value.name||value.tool_name||'').toLowerCase();if(name.includes('search')||name.includes('web'))tools.web++;else if(name.includes('python')||name.includes('code'))tools.code++;else if(name.includes('image'))tools.image_out++;else if(name.includes('video'))tools.video++;}const texts=[];for(const key of ['text','content','parts','body','value','output','result'])if(key in value){const[t,tc]=flattenContent(value[key]);tools=addTools(tools,tc);if(t)texts.push(t);}return[texts.join('\n'),tools];}return['',tools];}
function direction(role,text,tools){tools=toolCounts(tools);if(text.trim()==='[image]'){if(role==='user')tools.image_in++;else if(role==='assistant')tools.image_out++;}if(text.trim()==='[video]'&&role==='assistant')tools.video++;return tools;}
function msg(role,text,timestamp=null,tools=toolCounts()){return{role,text,timestamp,tools};}

export function parseChatGPT(payload){if(!Array.isArray(payload))return[];const out=[];payload.forEach((conv,idx)=>{if(!conv||typeof conv!=='object'||!conv.mapping||typeof conv.mapping!=='object')return;const mapping=conv.mapping;let leaf=conv.current_node;const chain=[],seen=new Set();while(leaf&&mapping[leaf]&&!seen.has(leaf)){seen.add(leaf);chain.push(mapping[leaf]);leaf=mapping[leaf]?.parent;}chain.reverse();const messages=[];let pending=toolCounts();for(const node of chain){const m=node?.message;if(!m||typeof m!=='object')continue;const role=normalRole(m.author?.role||m.role);if(!['user','assistant'].includes(role))continue;const content=m.content||{};let[text,tools]=flattenContent(content&&typeof content==='object'&&'parts'in content?content.parts:content);const md=m.metadata||{};let mdS='';try{mdS=JSON.stringify(md).toLowerCase();}catch{}const recipient=String(m.recipient||'').toLowerCase();if(role==='assistant'){if(mdS.includes('search_query')||recipient.includes('web.run')||recipient==='web'||recipient.startsWith('web.'))tools.web++;if(recipient.includes('python')||mdS.includes('code_interpreter'))tools.code++;if(recipient.includes('image_gen'))tools.image_out++;}tools=direction(role,text,tools);if(role==='assistant'&&!text.trim()&&(tools.web||tools.code||tools.image_out||tools.video)){pending=addTools(pending,tools);continue;}if(role==='assistant')tools=addTools(tools,pending),pending=toolCounts();if(text.trim())messages.push(msg(role,text.trim(),m.create_time?String(m.create_time):null,tools));}if(messages.length)out.push({provider:'ChatGPT',title:String(conv.title||`ChatGPT conversation ${idx+1}`),messages,source_format:'chatgpt-export-json',conversation_id:String(conv.id||idx),warnings:[]});});return out;}

export function parseClaude(payload){const entries=Array.isArray(payload)?payload:(payload&&Array.isArray(payload.conversations)?payload.conversations:[]);const out=[];entries.forEach((conv,idx)=>{if(!conv||!Array.isArray(conv.chat_messages))return;const messages=[];for(const m of conv.chat_messages){const role=normalRole(m.sender||m.role);if(!['user','assistant'].includes(role))continue;let[text,tools]=flattenContent(m.text!=null?m.text:m.content);const atts=m.attachments||m.files||[];if(Array.isArray(atts))for(const a of atts){let s='';try{s=JSON.stringify(a).toLowerCase();}catch{}if(role==='user'&&['image/','.png','.jpg','.jpeg','.webp'].some(x=>s.includes(x)))tools.image_in++;if(['.pdf','.docx','application/pdf'].some(x=>s.includes(x)))tools.document++;}tools=direction(role,text,tools);if(text.trim())messages.push(msg(role,text.trim(),m.created_at||null,tools));}if(messages.length)out.push({provider:'Claude',title:String(conv.name||conv.title||`Claude conversation ${idx+1}`),messages,source_format:'claude-export-json',conversation_id:String(conv.uuid||conv.id||idx),warnings:[]});});return out;}

function stripHtmlString(s=''){if(typeof DOMParser==='undefined')return String(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim();const d=new DOMParser().parseFromString(String(s),'text/html');d.querySelectorAll('script,style,noscript,svg').forEach(x=>x.remove());return(d.body?.innerText||d.body?.textContent||'').replace(/\n{3,}/g,'\n\n').trim();}
function sessionizeGemini(entries){entries.sort((a,b)=>(a.time||'').localeCompare(b.time||''));const groups=[];let cur=[];let prev=null;for(const e of entries){const t=e.time?Date.parse(e.time):NaN;if(cur.length&&prev!=null&&Number.isFinite(t)&&t-prev>30*60*1000){groups.push(cur);cur=[];}cur.push(e);if(Number.isFinite(t))prev=t;}if(cur.length)groups.push(cur);return groups.map((g,idx)=>{const messages=[];for(const e of g){if(e.prompt)messages.push(msg('user',e.prompt,e.time,visibleToolsFromText(e.prompt)));if(e.response)messages.push(msg('assistant',e.response,e.time,visibleToolsFromText(e.response)));}return{provider:'Gemini',title:(g[0]?.prompt||`Gemini activity ${idx+1}`).slice(0,80),messages,source_format:g[0]?.format||'gemini-takeout',warnings:['Gemini Takeout is an activity log; conversation grouping is reconstructed using a 30-minute gap and can be incomplete.']};}).filter(x=>x.messages.length);}
export function parseGeminiJson(payload){if(!Array.isArray(payload))return[];const entries=[];for(const r of payload){if(!r||typeof r!=='object')continue;const title=String(r.title||'');if(!/^(Prompted|Said)\s+/i.test(title))continue;const prompt=title.replace(/^(Prompted|Said)\s+/i,'').trim();const items=Array.isArray(r.safeHtmlItem)?r.safeHtmlItem:[];const response=items.map(x=>x&&typeof x==='object'?stripHtmlString(x.html||''):'').filter(Boolean).join(' ').trim();entries.push({prompt,response,time:String(r.time||''),format:'gemini-takeout-json'});}return sessionizeGemini(entries);}
export function parseGeminiHtml(html){const doc=new DOMParser().parseFromString(html,'text/html');const cells=[...doc.querySelectorAll('div.outer-cell,.outer-cell')];const entries=[];for(const cell of cells){const txt=(cell.innerText||cell.textContent||'').replace(/\s+/g,' ').trim();const p=txt.match(/\b(?:Prompted|Said)\s+(.+?)(?=(?:\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\b|$))/i);if(!p)continue;const rm=txt.match(/\bResponse\s*:\s*(.+)$/i);entries.push({prompt:p[1].trim(),response:rm?rm[1].trim():'',time:'',format:'gemini-takeout-html'});}return sessionizeGemini(entries);}

export function parseGenericJson(payload,provider='Unknown'){let entries=[];if(Array.isArray(payload))entries=payload;else if(payload&&typeof payload==='object'){for(const k of ['conversations','chats','threads','data'])if(Array.isArray(payload[k])){entries=payload[k];break;}if(!entries.length&&Array.isArray(payload.messages))entries=[payload];}const out=[];entries.forEach((conv,idx)=>{if(!conv||typeof conv!=='object')return;const raw=conv.messages||conv.turns||conv.chat_messages||conv.message_list;if(!Array.isArray(raw))return;const messages=[];for(const m of raw){if(!m||typeof m!=='object')continue;const role=normalRole(m.role||m.sender||m.author||m.from);if(!['user','assistant'].includes(role))continue;let[text,tools]=flattenContent(m.content??m.text??m.body??m.parts);tools=direction(role,text,tools);if(text.trim())messages.push(msg(role,text.trim(),m.created_at||m.timestamp||m.time||null,tools));}if(messages.length)out.push({provider,title:String(conv.title||conv.name||conv.subject||`${provider} conversation ${idx+1}`),messages,source_format:'generic-json',conversation_id:String(conv.id||conv.uuid||idx),warnings:['Generic export parser used; only visible recognized fields are counted.']});});return out;}

export function parseRoleText(text,provider='Unknown',format='pasted-text'){const matches=[...text.matchAll(new RegExp(ROLE_RE.source,ROLE_RE.flags))];if(!matches.length)return[];const messages=[];for(let i=0;i<matches.length;i++){const m=matches[i];const start=m.index+m[0].length,end=i+1<matches.length?matches[i+1].index:text.length;const body=text.slice(start,end).trim(),role=normalRole(m[1]);if(['user','assistant'].includes(role)&&body)messages.push(msg(role,body,null,visibleToolsFromText(body)));}return messages.length?[{provider,title:'Imported conversation',messages,source_format:format,warnings:[]}]:[];}

export function parseHtmlConversation(html,providerHint='Unknown'){const doc=new DOMParser().parseFromString(html,'text/html');if((doc.body?.textContent||'').includes('Gemini Apps')||(doc.body?.textContent||'').includes('Prompted')){const g=parseGeminiHtml(html);if(g.length)return g;}const messages=[];for(const el of doc.querySelectorAll('[data-message-author-role]')){const role=normalRole(el.getAttribute('data-message-author-role'));if(!['user','assistant'].includes(role))continue;const text=(el.innerText||el.textContent||'').trim();if(text)messages.push(msg(role,text,null,visibleToolsFromText(text)));}if(messages.length)return[{provider:providerHint,title:'Saved web conversation',messages,source_format:'html',warnings:[]}];doc.querySelectorAll('script,style,noscript,svg').forEach(x=>x.remove());const visible=(doc.body?.innerText||doc.body?.textContent||'');return parseRoleText(visible,providerHint,'html');}
export function providerHint(name='',text=''){const s=(name+' '+String(text).slice(0,5000)).toLowerCase();if(s.includes('chatgpt')||s.includes('openai'))return'ChatGPT';if(s.includes('claude')||s.includes('anthropic'))return'Claude';if(s.includes('gemini')||s.includes('bard'))return'Gemini';if(s.includes('grok')||s.includes('x.ai'))return'Grok';if(s.includes('deepseek'))return'DeepSeek';return'Unknown';}
