function shareIdFromUrl(rawUrl){try{const u=new URL(String(rawUrl).trim());if(!/(^|\.)chatgpt\.com$/i.test(u.hostname))return null;return u.pathname.match(/^\/share\/([0-9a-f-]{16,})/i)?.[1]||null;}catch{return null;}}

function parseJsonFromText(text){const raw=String(text||'').trim(),candidates=[raw];const fenced=raw.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1];if(fenced)candidates.push(fenced.trim());const a=raw.indexOf('{'),b=raw.lastIndexOf('}');if(a>=0&&b>a)candidates.push(raw.slice(a,b+1));for(const c of candidates){try{const v=JSON.parse(c);if(v&&typeof v==='object')return v;}catch{}}return null;}

async function fetchShareJson(id){const api=`https://chatgpt.com/backend-api/share/${id}`;for(const url of [api,`https://r.jina.ai/${api}`]){try{const r=await fetch(url,{headers:{Accept:'application/json,text/plain;q=0.9,*/*;q=0.8'}});if(!r.ok)continue;const data=parseJsonFromText(await r.text());if(data)return data;}catch{}}throw new Error('Could not retrieve this ChatGPT shared conversation.');}

function orderedNodes(share){if(Array.isArray(share?.linear_conversation)&&share.linear_conversation.length)return share.linear_conversation;const map=share?.mapping&&typeof share.mapping==='object'?share.mapping:null;if(!map)return[];const root=Object.keys(map).find(id=>!map[id]?.parent)||Object.keys(map)[0],out=[],seen=new Set();let id=root;while(id&&map[id]&&!seen.has(id)){seen.add(id);out.push(map[id]);const children=Array.isArray(map[id].children)?map[id].children:[];id=children.find(x=>map[x])||null;}return out.length?out:Object.values(map);}
function roleOf(msg){const r=String(msg?.author?.role||msg?.role||'').toLowerCase();if(['user','human','you'].includes(r))return'user';if(['assistant','model','chatgpt','bot'].includes(r))return'assistant';if(r==='tool')return'tool';return r;}
function deepWalk(value,visit,seen=new WeakSet()){if(value==null||typeof value!=='object'||seen.has(value))return;seen.add(value);visit(value);if(Array.isArray(value))for(const x of value)deepWalk(x,visit,seen);else for(const x of Object.values(value))deepWalk(x,visit,seen);}
function visibleText(msg){const c=msg?.content||{},type=String(c.content_type||'').toLowerCase();if(['model_editable_context','thoughts','reasoning_recap'].includes(type))return'';const chunks=[];for(const p of Array.isArray(c.parts)?c.parts:[]){if(typeof p==='string'&&p.trim())chunks.push(p.trim());else if(p&&typeof p==='object'&&typeof p.text==='string'&&p.text.trim())chunks.push(p.text.trim());}if(typeof c.text==='string'&&c.text.trim())chunks.push(c.text.trim());return[...new Set(chunks)].join('\n\n').trim();}
function ext(name=''){return String(name).toLowerCase().match(/\.([a-z0-9]{1,8})(?:[?#].*)?$/)?.[1]||'';}
function kindFrom(name='',mime='',type=''){const e=ext(name),m=String(mime).toLowerCase(),t=String(type).toLowerCase();if(m.startsWith('image/')||t.includes('image')||['png','jpg','jpeg','webp','gif','bmp','svg'].includes(e))return'image';if(m.startsWith('video/')||t.includes('video')||['mp4','mov','avi','webm','mkv'].includes(e))return'video';if(m.startsWith('application/pdf')||m.includes('officedocument')||m.includes('spreadsheet')||m.includes('presentation')||m.startsWith('text/')||t.includes('file')||['pdf','doc','docx','txt','md','rtf','csv','tsv','xlsx','xls','ppt','pptx','tex','zip','json'].includes(e))return'document';return null;}
function structuredFiles(obj){const refs=[];deepWalk(obj,node=>{const name=node.name||node.filename||node.title||'',mime=node.mime_type||node.mimeType||node.mimetype||node.mime||'',type=node.type||node.content_type||'',pointer=node.asset_pointer||node.image_asset_pointer||node.video_asset_pointer||node.file_id||node.id||node.download_url||node.url,kind=kindFrom(name,mime,type);if(!kind||!(pointer||name||mime))return;refs.push({id:String(pointer||`${name}|${mime}`),kind,name:String(name)});});const seen=new Map();for(const r of refs)if(!seen.has(r.id))seen.set(r.id,r);return[...seen.values()];}
function visibleLinkedFiles(text=''){const refs=[],re=/(?:sandbox:)?\/mnt\/data\/[^\s)\]}'\"<>]+/g;for(const m of String(text).matchAll(re)){let path=m[0].replace(/[.,;:!?]+$/,'');const kind=kindFrom(path,'','file');if(kind)refs.push({id:path.replace(/^sandbox:/,''),kind,name:path});}const seen=new Map();for(const r of refs)if(!seen.has(r.id))seen.set(r.id,r);return[...seen.values()];}
function toolCategory(name=''){const n=String(name).toLowerCase();if(/web\.run|browser|search|browse/.test(n))return'web';if(/python|container\.|code[_-]?interpreter|jupyter|notebook/.test(n))return'code';if(/image[_-]?gen|text2im|dall/.test(n))return'image';if(/video[_-]?gen|text2video|sora/.test(n))return'video';return'other';}
function newTurn(userText='',uploads={}){return{userText,assistantParts:[],uploadedImages:new Set(uploads.images||[]),uploadedDocuments:new Set(uploads.documents||[]),generatedImages:new Set(),generatedVideos:new Set(),generatedDocuments:new Set(),toolCalls:0,web:0,code:0,imageToolCalls:0,videoToolCalls:0};}
function finish(turns,t){if(!t)return null;const assistantText=t.assistantParts.join('\n\n').trim(),active=assistantText||t.toolCalls||t.generatedImages.size||t.generatedVideos.size||t.generatedDocuments.size||t.uploadedImages.size||t.uploadedDocuments.size;if(active)turns.push({userText:t.userText,assistantText,uploadedImages:t.uploadedImages.size,uploadedDocuments:t.uploadedDocuments.size,generatedImages:t.generatedImages.size,generatedVideos:t.generatedVideos.size,generatedDocuments:t.generatedDocuments.size,toolCalls:t.toolCalls,web:t.web,code:t.code,imageToolCalls:t.imageToolCalls,videoToolCalls:t.videoToolCalls});return null;}

export function parseChatGptShare(share){const turns=[];let open=null,pendingUser='',pendingUploads={images:[],documents:[]};let currentToolCalls=new Set();for(const node of orderedNodes(share)){const msg=node?.message||node;if(!msg||typeof msg!=='object')continue;const role=roleOf(msg),md=msg.metadata||{};if(!['user','assistant','tool'].includes(role)||md.is_visually_hidden_from_conversation)continue;const text=visibleText(msg),files=structuredFiles(msg);if(role==='user'){open=finish(turns,open);currentToolCalls=new Set();const images=[],documents=[];for(const f of files){if(f.kind==='image')images.push(f.id);else if(f.kind==='document')documents.push(f.id);}pendingUser=pendingUser?`${pendingUser}\n\n${text}`.trim():text;pendingUploads={images:[...new Set(images)],documents:[...new Set(documents)]};continue;}if(!open)open=newTurn(pendingUser,pendingUploads);pendingUser='';pendingUploads={images:[],documents:[]};if(role==='assistant'){const recipient=String(msg.recipient||'').toLowerCase();if(recipient&&recipient!=='all'){const key=String(msg.id||node.id||`${recipient}:${turns.length}:${open.toolCalls}`);if(!currentToolCalls.has(key)){currentToolCalls.add(key);open.toolCalls++;const cat=toolCategory(recipient);if(cat==='web')open.web++;else if(cat==='code')open.code++;else if(cat==='image')open.imageToolCalls++;else if(cat==='video')open.videoToolCalls++;}}else if(text){open.assistantParts.push(text);for(const f of visibleLinkedFiles(text)){if(f.kind==='document')open.generatedDocuments.add(f.id);else if(f.kind==='video')open.generatedVideos.add(f.id);}}continue;}const author=String(msg?.author?.name||'').toLowerCase(),cat=toolCategory(author),explicitImage=Boolean(md.image_gen_title)||cat==='image',explicitVideo=Boolean(md.video_gen_title)||cat==='video';for(const f of files){if(f.kind==='image'&&explicitImage)open.generatedImages.add(f.id);else if(f.kind==='video'&&explicitVideo)open.generatedVideos.add(f.id);}if(explicitImage&&!files.some(f=>f.kind==='image'))open.generatedImages.add(String(msg.id||md.image_gen_title||`img:${turns.length}`));if(explicitVideo&&!files.some(f=>f.kind==='video'))open.generatedVideos.add(String(msg.id||md.video_gen_title||`vid:${turns.length}`));}finish(turns,open);if(!turns.length)throw new Error('No readable ChatGPT turns were found in this share.');return{title:String(share?.title||'Shared ChatGPT conversation'),turns};}
export async function loadShare(rawUrl){const id=shareIdFromUrl(rawUrl);if(!id)throw new Error('Paste a public ChatGPT share link.');return parseChatGptShare(await fetchShareJson(id));}
